name: Vercel Preview Deployment

on:
  - pull_request

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Preview deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
